FROM centos:7.3.1611
RUN yum install -y epel-release
RUN yum clean all && yum makecache
RUN yum install -y git gcc-c++ vim python36 python36-devel \
    python36-pip wget curl java-1.8.0-openjdk-devel make autoconf automake\
    supervisor python36-pip python36-virtualenv unzip sshpass

# 设置语言环境为UTF-8
RUN locale
RUN localedef -i zh_CN -c -f UTF-8 zh_CN.UTF-8
RUN echo "export LC_ALL=zh_CN.UTF-8" >> /etc/profile && source /etc/profile
ENV LANG zh_CN.UTF-8
ENV LC_CTYPE zh_CN.UTF-8

# 安装JDK
WORKDIR /opt/app
ADD http://10.128.2.12:8081/repository/aiops-raw/aiops/jdk/1.8.0.144/jdk-1.8.0.144.zip .
RUN unzip ./jdk-1.8.0.144.zip
RUN rm -Rf ./jdk-1.8.0.144.zip

# 安装Node-JS
ADD http://10.128.2.12:8081/repository/aiops-raw/aiops/nodejs/10.16.3/nodejs-10.16.3.tar .
RUN tar xvf ./nodejs-10.16.3.tar 
RUN rm -Rf ./nodejs-10.16.3.tar

# 安装Maven
ADD http://10.128.2.12:8081/repository/aiops-raw/aiops/maven/3.6.2/maven-3.6.2.tar .
RUN tar xzvf ./maven-3.6.2.tar
RUN rm -Rf ./maven-3.6.2.tar

# 安装GoLang
ADD http://10.128.2.12:8081/repository/aiops-raw/aiops/golang/1.13/golang-1.13.tar .
RUN tar xzvf ./golang-1.13.tar
RUN rm -Rf ./golang-1.13.tar
RUN mkdir -p /opt/gopath

# 写入环境变量
ENV JAVA_HOME /opt/app/jdk1.8.0_144
ENV MAVEN_HOME /opt/app/maven-3.6.2
ENV NODE_HOME /opt/app/node-v10.16.3-linux-x64
ENV GO_ROOT /opt/app/go 
ENV GO_PATH /opt/gopath
ENV PATH $PATH:/opt/app/jdk-1.8.0.144/bin:/opt/app/maven-3.6.2/bin:/opt/app/node-v10.16.3-linux-x64/bin/:/opt/app/go/bin

# Python设置为国内源
RUN mkdir -p /root/.pip
ADD ./pip.conf /root/.pip

# NodeJS设置为淘宝源
WORKDIR /opt/app/node-v10.16.3-linux-x64/bin
RUN ./npm config set strict-ssl false && \
    ./node ./npm install -g yarn && \
    ./node ./npm config set registry https://registry.npm.taobao.org &&\
    ./node ./npm config set disturl https://npm.taobao.org/dist&&\
    ./node ./npm config set electron_mirror https://npm.taobao.org/mirrors/electron/&&\
    ./node ./npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/&&\
    ./node ./npm config set phantomjs_cdnurl https://npm.taobao.org/mirrors/phantomjs/&&\
    ./node ./yarn config set registry https://registry.npm.taobao.org -g&&\
    ./node ./yarn config set disturl https://npm.taobao.org/dist -g&&\
    ./node ./yarn config set electron_mirror https://npm.taobao.org/mirrors/electron/ -g&&\
    ./node ./yarn config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/ -g&&\
    ./node ./yarn config set phantomjs_cdnurl https://npm.taobao.org/mirrors/phantomjs/ -g&&\
    ./node ./yarn config set chromedriver_cdnurl https://cdn.npm.taobao.org/dist/chromedriver -g&&\
    ./node ./yarn config set operadriver_cdnurl https://cdn.npm.taobao.org/dist/operadriver -g&&\
    ./node ./yarn config set fse_binary_host_mirror https://npm.taobao.org/mirrors/fsevents -g

WORKDIR /opt
